version: '3.8'
services:
  db: 
    image: mysql:latest
    container_name: mysqldb-GoEcom
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: GoEcom
      MYSQL_USER: fran
      MYSQL_PASSWORD: 1234
    ports:
      - 3306:3306
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
